import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/Main'
import Projects from '../components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sergio Rivera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Projects />
    </div>
  )
}
