import Head from 'next/head'
import About from '../components/About'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Script from 'next/script'

export default function Home() {
  return (
    <div>
      <Head>
        <Script 
          src="https://www.googletagmanager.com/gtag/js?id=G-DWXCRR7P72" 
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-DWXCRR7P72');
          `}
        </Script>
        <title>Sergio Rivera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Projects />
    </div>
  )
}
